#!/bin/zsh
# dev/spike-body.sh FIXTURE
#
# Spike (e), the canonical body (M0 Stage 0, R-M0-6).
# Generates a bash 3.2 fragment that carries FIXTURE as a quoted heredoc
# into a shell variable, runs that assignment under /bin/bash, prints the
# variable with printf '%s', and compares the extracted bytes with the
# fixture bytes.
#
# Prints:  BODY-SAME sha256=<x> sha1=<y> bytes=<n>        and exits 0
#      or  BODY-DIFF sha256_heredoc=<x> sha256_file=<y>   and exits 1
# The sha1 is the EVALSHA key, so it prints too.
#
# The fragment and the extracted bytes land under
# /Users/oobi/Documents/tether-m0/spikes/body/ (override with SPIKE_BODY_DIR).
# Scratch never enters the repository.
set -eu

case "${1:-}" in
  '')
    printf 'usage: dev/spike-body.sh FIXTURE\n' >&2
    exit 4
    ;;
  *)
    fixture="$1"
    ;;
esac

case "$(test -f "$fixture" && printf 'file' || printf 'missing')" in
  file) ;;
  missing)
    printf 'spike-body: not a file: %s\n' "$fixture" >&2
    exit 4
    ;;
  *) exit 4 ;;
esac

out_dir="${SPIKE_BODY_DIR:-/Users/oobi/Documents/tether-m0/spikes/body}"
mkdir -p "$out_dir"

stem="$(basename "$fixture")"
stem="${stem%.*}"
frag="$out_dir/$stem.fragment.sh"
extracted="$out_dir/$stem.extracted"
delim='TETHER_LUA_EOF'

# The fragment.  A quoted heredoc delimiter keeps every byte literal, so no
# expansion and no backslash processing touches the body.  Command
# substitution strips the one newline the heredoc form adds before the
# delimiter line, which is why the canonical body ends without a newline.
{
  printf '# bash 3.2 fragment, generated by dev/spike-body.sh on 2026-09-09\n'
  printf '# source: %s\n' "$fixture"
  printf "LUA_BODY=\$(cat <<'%s'\n" "$delim"
  cat "$fixture"
  printf '\n%s\n)\n' "$delim"
} > "$frag"

# Run the assignment under /bin/bash (3.2 on this host) and print the variable.
/bin/bash -c '. "$1" && printf "%s" "$LUA_BODY"' spike-body "$frag" > "$extracted"

sha256_heredoc="$(shasum -a 256 < "$extracted" | cut -d ' ' -f 1)"
sha256_file="$(shasum -a 256 < "$fixture" | cut -d ' ' -f 1)"
sha1_heredoc="$(shasum -a 1 < "$extracted" | cut -d ' ' -f 1)"
bytes="$(wc -c < "$extracted" | tr -d ' ')"

case "$(test "$sha256_heredoc" = "$sha256_file" && printf 'same' || printf 'diff')" in
  same)
    printf 'BODY-SAME sha256=%s sha1=%s bytes=%s\n' "$sha256_heredoc" "$sha1_heredoc" "$bytes"
    exit 0
    ;;
  diff)
    printf 'BODY-DIFF sha256_heredoc=%s sha256_file=%s\n' "$sha256_heredoc" "$sha256_file"
    exit 1
    ;;
  *) exit 4 ;;
esac
